"""
LLM explanation service (Google Gemini).

This module is the "LLM Explanation Generator" stage of the Applied AI
architecture (see diagrams/architecture.mmd). It turns the grounded context
built in src/explanations.py into a friendly, natural-language explanation.

It is intentionally strict: it either returns a real generated explanation or
raises LLMServiceError. It NEVER returns fallback text - the caller is
responsible for falling back to build_fallback_explanation when this raises.

Configuration:
    GEMINI_API_KEY must be set (loaded from a .env file via python-dotenv).
"""

import logging
import os
from typing import Optional

from dotenv import load_dotenv
from google import genai

logger = logging.getLogger(__name__)

# Load variables from .env when this module is imported. Tests can still
# override or remove environment variables using monkeypatch.
load_dotenv()

# A lightweight, fast model that is well suited to short text generation.
MODEL = "gemini-3.6-flash"

# Word budget requested from the model for the explanation.
MIN_WORDS = 80
MAX_WORDS = 120


class LLMServiceError(Exception):
    """Raised when a grounded explanation cannot be generated by the LLM."""


def generate_explanation(context: str) -> str:
    """Generate a grounded, natural-language explanation from a context string.

    Args:
        context: the grounded facts produced by
            explanations.build_recommendation_context.

    Returns:
        The generated explanation text.

    Raises:
        LLMServiceError: if the context is empty, the API key is missing, the
            request fails, or Gemini returns no usable text.
    """
    if not isinstance(context, str) or not context.strip():
        raise LLMServiceError("context must be a non-empty string")

    client = _build_client()
    prompt = _build_prompt(context)

    try:
        response = client.models.generate_content(model=MODEL, contents=prompt)
    except Exception as exc:  # any SDK / network error becomes our error type
        logger.warning("Gemini request failed: %s", exc)
        raise LLMServiceError(f"Gemini request failed: {exc}") from exc

    text: Optional[str] = getattr(response, "text", None)
    if not text or not text.strip():
        logger.warning("Gemini returned no text")
        raise LLMServiceError("Gemini returned no text")

    logger.info("Gemini generated an explanation (%d chars)", len(text))
    return text.strip()


def _build_client() -> genai.Client:
    """Create a Gemini client, requiring GEMINI_API_KEY to be present."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise LLMServiceError("GEMINI_API_KEY is not set")
    return genai.Client(api_key=api_key)


def _build_prompt(context: str) -> str:
    """Build the grounded instruction prompt sent to Gemini."""
    return (
        "You are a helpful music assistant. Using ONLY the information in the "
        "context below, explain in a warm, friendly, and natural tone WHY these "
        "song recommendations fit the listener's preferences.\n\n"
        "Strict rules:\n"
        "- Use only facts that appear in the context.\n"
        "- Never invent songs, artists, genres, moods, or audio features.\n"
        "- Do not mention scores, numbers, or internal scoring reasons directly.\n"
        f"- Keep the explanation concise, roughly {MIN_WORDS}-{MAX_WORDS} words.\n"
        "- Refer to the top recommendation by its title.\n\n"
        "Context:\n"
        f"{context}\n\n"
        "Explanation:"
    )
